name: tuev-tfm_pretrained
group: B
dataset: tuev
data_root: $PACLOCK_PROC/processed_tfm/tuev
model: tfm
loader: tfm
pretrained: true
tfm_setting: single
optimizer: adamw
lr: 0.001
weight_decay: 1.0e-05
epochs: 2
batch_size: 64
scheduler: cosine
grad_clip: null
patience: 2
num_workers: 16
device: cuda
eval_every_steps: 0
num_classes: 6
sample_rate: 200
loss: cross_entropy
label_smoothing: 0.0
seed: 0
