name: sleepedf-contrawr
group: A
model: contrawr
dataset: sleepedf
data_root: /work1/chenyuyou/yifanwang/Zhizhe/processed/sleepedf
num_classes: 5
sample_rate: 100
loss: cross_entropy
batch_size: 64
num_workers: 16
epochs: 1
lr: 0.0001
weight_decay: 1.0e-05
scheduler: cosine
grad_clip: 1.0
patience: 10
eval_every_steps: 0
seed: 0
device: cuda
label_smoothing: 0.1
model_kwargs:
  token_size: 100
