name: tuab-sparcnet
group: A
model: sparcnet
dataset: tuab
data_root: /work1/chenyuyou/yifanwang/Zhizhe/processed/tuab
num_classes: 2
sample_rate: 200
loss: bce_with_logits
batch_size: 64
num_workers: 16
epochs: 1
lr: 0.0001
weight_decay: 1.0e-05
scheduler: cosine
grad_clip: 1.0
patience: 6
eval_every_steps: 0
seed: 0
device: cuda
